### PR TITLE
Introduce analyzers and general code cleanup

### PR DESCRIPTION
**Pull request by glennawatson**

### CODE REVIEW

**Comment by glennawatson** [comment]
Might be worth testing this version before committing locally.

**Comment by glennawatson** [comment]
@maxrumsey would recommend you merge after testing sooner rather than later after you test locally, due to the large formatting changes merging can be a bit nightmareish.

**Comment by maxrumsey** [comment]
Thanks for the PR Glenn! I'll get on it tomorrow, and don't intend on pushing anything new before this. Having a quick squizz, the codebase definitely looks way more understandable!

**Comment by maxrumsey** [comment]
I've just merged this into the development branch! There's a few issues I need to take care of (Crashing on startup if a vatSys connection is already established, issues with the Take Off Timer), but I'll sort them from my end. Thanks again Glenn!

**Pull request closed without merging**
